version: "3.4"

name: apposite

networks:
  apposite:
    driver: bridge

services:
  apposite-service:
    depends_on:
      - apposite-db
      - apposite-elasticsearch
      - apposite-rabbitmq
      - apposite-redis
    container_name: apposite-service
    restart: on-failure
    ports:
      - "127.0.0.1:31260:80"
      - "127.0.0.1:31261:443"
    build:
      context: .
      dockerfile: ./Apposite.Api/Dockerfile
    volumes:
      - ./certificate.pfx:/app/certificate.pfx
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
      - ASPNETCORE_URLS=https://+:443;https://+:80
      - ASPNETCORE_Kestrel__Certificates__Default__Password=Hesoyam%56
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/app/certificate.pfx
    networks:
      - apposite
    links:
      - apposite-db
      - apposite-rabbitmq
      - apposite-elasticsearch
      - apposite-redis
      - apposite-fastapi-app

  apposite-fastapi-app:
    image: "tahamuslu/intelligrade-python-ai:latest"
    container_name: apposite-fastapi-app
    environment:
      OPENAI_API_KEY: "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"
      GOOGLE_AI_API_KEY: "AIzaSyCC9Csv_8ygRg7GIH90ljGbY2vqoMzVtm0"
    working_dir: /app
    volumes:
      - ../apposite-fastapi:/app
    command: bash -c "pip install -r requirements.txt && uvicorn main:app --host 0.0.0.0 --port 80"
    ports:
      - "9123:80"
    networks:
      - apposite

  apposite-db:
    image: postgres:latest
    container_name: apposite-db
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
    ports:
      - "5432:5432"
    restart: always
    networks:
      - apposite
    hostname: "apposite-db"

  apposite-elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.6.2
    container_name: apposite-elasticsearch
    restart: always
    environment:
      - xpack.security.enabled=false
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    cap_add:
      - IPC_LOCK
    ports:
      - 9200:9200
      - 9300:9300
    networks:
      - apposite
    hostname: "apposite-elasticsearch"

  apposite-redis:
    image: redis
    container_name: apposite-redis
    ports:
      - 6380:6379
    hostname: "apposite-redis"
    networks:
      - apposite

  apposite-rabbitmq:
    image: rabbitmq:3-management
    hostname: "apposite-rabbitmq"
    labels:
      NAME: "rabbitmq"
    container_name: "apposite-rabbitmq"
    ports:
      - "5673:5671"
      - "5674:5672"
      - "15673:15672"
    environment:
      - RABBITMQ_DEFAULT_PASS:M@gnet
      - RABBITMQ_DEFAULT_USER:magnet
    networks:
      - apposite
