name: Deploy to VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: SSH into VPS and Pull Changes
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          password: ${{ secrets.VPS_PASS }}
          script: |
            cd apposite
            git checkout main
            git pull
            cd ..
            cd apposite-fastapi
            git checkout main
            git pull

      - name: Docker compose down and remove image
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          password: ${{ secrets.VPS_PASS }}
          script: |
            cd apposite
            docker-compose down
            docker rmi apposite-apposite-service
            docker builder prune
        continue-on-error: true

      - name: Run Docker Compose
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          password: ${{ secrets.VPS_PASS }}
          script: |
            cd apposite
            docker-compose up -d
